# Generated by Django 5.2.8 on 2025-11-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='university.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='university.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='university.admin')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='university.department')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateStudent',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='graduate', serialize=False, to='university.student')),
                ('degree', models.CharField(max_length=200)),
                ('g_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateStudent',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='undergraduate', serialize=False, to='university.student')),
                ('major', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='university.admin')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='university.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveIntegerField()),
                ('term', models.CharField(max_length=50)),
                ('total_capacity', models.PositiveIntegerField()),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('remaining_capacity', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='university.admin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='university.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='university.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('midterm_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='university.admin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='university.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.section')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='university.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.section')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitlist_id', models.PositiveIntegerField()),
                ('spaces_left', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlists', to='university.admin')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to='university.section')),
            ],
        ),
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wait_entries', to='university.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_entries', to='university.student')),
                ('waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='university.waitlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'section_number'), name='unique_course_section_number'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('section', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'section')},
        ),
        migrations.AddConstraint(
            model_name='waitlist',
            constraint=models.UniqueConstraint(fields=('section', 'waitlist_id'), name='unique_section_waitlist'),
        ),
        migrations.AlterUniqueTogether(
            name='wait',
            unique_together={('student', 'waitlist')},
        ),
    ]
